name: Update Chess Rating

on:
  schedule:
    - cron: '0 10 * * *'  # 5 AM EST (10 AM UTC)
  workflow_dispatch:

jobs:
  update-rating:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: python update_rating.py
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Update rating"
        git push
